Agora-Archive/codingtest-study

seunghyun/[WEEK8] 과제 제출/main.cpp

[Update] main.cpp

---

seungje/5430 - AC/5430.cpp
seungje/5430 - AC/5430.md

https://www.acmicpc.net/problem/5430

AC 리뷰 부탁드립니다

---

gardenZero/2170-선긋기/선긋기.cpp

선긋기 리뷰 부탁해요~

---

sunan/백준 2579번_계단오르기/2579.java

[ADD] 2579.java 리뷰요청

---

seungje/15663 - N과M(9)/15663.cpp
seungje/15663 - N과M(9)/15663.md

https://www.acmicpc.net/problem/15663

[15663 - N과m(9)] 리뷰 부탁드립니다

---

gardenZero/2447 - 별찍기/README.md
gardenZero/2447 - 별찍기/별찍기.cpp

solved 2447

---

seungje/2263 - 트리의 순회/2263.cpp
seungje/2263 - 트리의 순회/2263.md

https://www.acmicpc.net/problem/2263

[2263 - 트리의 순회] 리뷰 부탁드립니다

---

seungje/1693 - 숨바꼭질/1693.cpp
seungje/1693 - 숨바꼭질/1693.md

https://www.acmicpc.net/problem/1697

[1693-숨바꼭질] 리뷰 부탁드립니다

---

jungminju/완전이진트리(9934)/Main.java
jungminju/완전이진트리(9934)/readme.md

완전이진트리(9934)

---

seungje/1238 - 파티/1238.cpp
seungje/1238 - 파티/1238.md

https://www.acmicpc.net/problem/1238

[1238 - 파티] 리뷰 부탁드립니다

---

gardenZero/16987 - 계란으로 계란치기/16987.cpp
gardenZero/16987 - 계란으로 계란치기/README.md

solved 16987

---

jungminju/포도주 시식(2156)/Main.java

[https://velog.io/@jung-min-ju/%EB%B0%B1%EC%A4%80-%ED%8F%AC%EB%8F%84%EC%A3%BC-%EC%8B%9C%EC%8B%9D](url)

[add] 포도주 시식

---

seungje/2992 - 크면서 작은 수/2992.java
seungje/2992 - 크면서 작은 수/2992.md

https://www.acmicpc.net/problem/2992

add: 2992 업로드

---

jungminju/고층건물-1027/Main.java

처음에는 가장 큰 빌딩을 구한 후, 왼쪽과 오른쪽으로 나뉘어서 구하려고 했지만 해당 방법으로 하면 코드가 더 복잡해질 것이 예상되어 아래와 같이 구하게 되었다.
1. 처음부터 끝까지 오른쪽 빌딩만 본다.
2. 바로 옆 빌딩은 무조건 볼 수 있기 때문에 for문 진입 전 미리 ++를 해준다.
(양방향으로 ++를 해줘야 한다.)
3. 바로 옆 빌딩과의 기울기를 기준선으로 잡는다.
4.  그 다음(즉 오른쪽 방향으로 옆옆 빌딩부터 시작)  for문으로 진입하여 새로운 빌딩과의 기울기가 기준선의 기울기보다 더 크다면, 기준선을 갱신 후 볼 수 있는 빌딩으로 간주한다.
[블로그주소](https://velog.io/@jung-min-ju/%EB%B0%B1%EC%A4%80-%EA%B3%A0%EC%B8%B5%EA%B1%B4%EB%AC%BC1027)

고층건물 코드 리뷰 부탁드립니다.

---

seungje/2098 - 외판원 순회 1/2098.java
seungje/2098 - 외판원 순회 1/2098.md

https://www.acmicpc.net/problem/2098
readme 참고하세용

add: 2098 업로드

---

jungminju/지금 자면 꿈을 꾸지만 - 32029/Main.java

이번에 준비한 문제는 "지금 자면 꿈을 꾸지만" 이라는 문제입니다.
해설은 다음 블로그를 참고해주세요!
[지금 자면 꿈을 꾸지만](https://velog.io/@jung-min-ju/%EB%B0%B1%EC%A4%80-%EC%A7%80%EA%B8%88-%EC%9E%90%EB%A9%B4-%EA%BF%88%EC%9D%84-%EA%BE%B8%EC%A7%80%EB%A7%8C32029)

지금 자면 꿈을 꾸지만

---

jungminju/사다리 타기-2469/Main.java
jungminju/사다리 타기-2469/README.md

[add] 사다리타기-2469

---

seungje/programmers - 이모티콘 할인 행사/이모티콘 할인 행사.java
seungje/programmers - 이모티콘 할인 행사/이모티콘 할인 행사.md

https://school.programmers.co.kr/learn/courses/30/lessons/150368

add: 이모티콘 할인 행사 upload

---

seungje/programmers - 등산 코스 정하기/등산 코스 정하기.java
seungje/programmers - 등산 코스 정하기/등산 코스 정하기.md

https://school.programmers.co.kr/learn/courses/30/lessons/118669

add: 등산 코스 정하기

---

gardenZero/17070 - 파이프 옮기기/17070.cpp
gardenZero/17070 - 파이프 옮기기/README.md

solved 17070

---

seungje/2239 - 스도쿠/2239.java
seungje/2239 - 스도쿠/2239.md

https://www.acmicpc.net/problem/2239

add : 2239 스도쿠

---

seungje/programmers - 행렬 테두리 회전하기/행렬 테두리 회전하기.java
seungje/programmers - 행렬 테두리 회전하기/행렬 테두리 회전하기.md

https://school.programmers.co.kr/learn/courses/30/lessons/77485

add: 행렬 테두리 회전하기 upload

---

jungminju/DFS 스페셜 저지 - 16964/Main.java
jungminju/DFS 스페셜 저지 - 16964/README.md

add: dfs 스페셜 저지

---

gardenZero/2638 - 치즈/2638.cpp
gardenZero/2638 - 치즈/README.md

solved 2638

---

jungminju/Z-1074/Main.java
jungminju/Z-1074/README.md
jungminju/피리 부는 사나이-16724/Main.java
jungminju/피리 부는 사나이-16724/README.md

add : 백준 피리 부는 사나이(16724) 추가
add : 백준 Z(1074) 추가

add : 백준 z(1074) 추가
